version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=abrus
      - GF_SECURITY_ADMIN_PASSWORD=abrus
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning/dashboards
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'  # Set retention policy to 15 days
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    network_mode: host
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - ./alert-manager/config:/etc/alertmanager
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

