route:
  receiver: email-alert-manager
  repeat_interval: 1m
receivers:
  - name: email-alert-manager
    email_configs:
      - to: 'yashar.ansari76@gmail.com'
        from: 'alert@abrus.org'
        smarthost: 'mail.example.com:465'
        auth_username: 'alert@example.com'
        auth_password: 'password'
